# Generated by Django 5.0.6 on 2024-07-30 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
